## Numpy

In [1]:
import numpy as np

1. Create an `ndarray` of shape (3,5). All values of the array are 100.

In [16]:
a = np.random.randint(100, 101, (3, 5))
a

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

2. Create a border of zeros that surround the result in Question 1, so that the output is of shape (5,7), the outside values are 0 and the inside values are 100. 

In [9]:
b = np.pad(a, pad_width=1, mode='constant', constant_values=0)
b

array([[  0,   0,   0,   0,   0,   0,   0],
       [  0, 100, 100, 100, 100, 100,   0],
       [  0, 100, 100, 100, 100, 100,   0],
       [  0, 100, 100, 100, 100, 100,   0],
       [  0,   0,   0,   0,   0,   0,   0]])

3. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.


In [10]:
c = np.diag(np.arange(1, 5), k = -1)
c

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

4. Create a checkerboard 8x8 matrix using the tile function

In [11]:
d = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
d

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

5. Sort a 2d-array by the nth column

In [22]:
e = np.random.randint(0, 10, (5, 3))
e
e[e[:, 1].argsort()]

array([[0, 1, 0],
       [7, 4, 7],
       [3, 5, 2],
       [1, 5, 5],
       [9, 9, 8]])

6. Compute a matrix rank

In [24]:
np.linalg.matrix_rank(e)

3

7. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [27]:
f = np.random.randint(0, 10, (5, 5, 3))
g = np.random.randint(0, 10, (5, 5))
print(f * g[:,:, np.newaxis])

[[[45 18 81]
  [ 6  0 14]
  [16 72 32]
  [ 0  0  0]
  [54 63 81]]

 [[32 32  0]
  [54 81 72]
  [ 0  0  0]
  [12 24 24]
  [ 7 56  7]]

 [[28  7 28]
  [28 14  0]
  [15  3  0]
  [ 8  6 12]
  [ 0  0  0]]

 [[ 2  9  0]
  [20 40 20]
  [40  8 16]
  [ 0  6 16]
  [ 8  8  4]]

 [[ 5  3  3]
  [36 54  6]
  [20 20  4]
  [ 0 28 63]
  [ 0  0  0]]]


8. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [32]:
h = np.ones((16,16))
k = 4
result = np.add.reduceat(np.add.reduceat(h, np.arange(0, h.shape[0], k), axis=0),
                                      np.arange(0, h.shape[1], k), axis=1)
result

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

9. Get the n largest values of an array

In [39]:
a = np.random.randint(0, 10, 10)
print(a)
a[a.argsort()][-2:]

[6 4 3 3 4 3 7 1 3 4]


array([6, 7])

10. Implement the Game of Life using numpy arrays

In [42]:
# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100):
    Z = iterate(Z)
print(Z.sum())

195


Check https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb for more Numpy exercises.

## Pandas

In [44]:
import pandas as pd
import seaborn as sb

1. Using NumPy, create a Pandas DataFrame with five rows and three columns

In [46]:
pd.DataFrame(np.random.randint(0, 10, (5, 3)))

0  1  2
0  2  9  5
1  6  9  6
2  9  9  7
3  0  1  3
4  3  2  5

The following six questions depend on the penguins dataset.

In [47]:
df_penguins = sb.load_dataset('penguins')

2. What function can we use to drop the rows that have missing data?

In [48]:
df_penguins.dropna()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
4         3450.0  Female  
5         3650.0    Male  
..           ...     ...  
338       4925.0  Female  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[333 rows x 7 columns]

3. By default, will the function in Question 2 modify df_penguins or will it return a copy? 

Return a copy, if inplace=True, then it will modify df_penguins

4. Let df_full be the dataframe obtained from dropping rows with missing data. What is the average bill length of a penguin, in millimeters, in this (df_full) data set?

In [50]:
df_full = df_penguins.dropna()
df_full['bill_length_mm'].mean()

43.992792792792805

5. Which species has the longest flippers?

In [69]:
df_full.groupby(['species']).agg({'flipper_length_mm':[np.mean, max]})

flipper_length_mm       
                       mean    max
species                           
Adelie           190.102740  210.0
Chinstrap        195.823529  212.0
Gentoo           217.235294  231.0

6. Which two species have the most similar mean weight?

In [70]:
df_full.groupby(['species'])['body_mass_g'].mean()

species
Adelie       3706.164384
Chinstrap    3733.088235
Gentoo       5092.436975
Name: body_mass_g, dtype: float64

7. How could you sort by species first, then by body mass?

In [73]:
df_full.sort_values(by=['species', 'body_mass_g']).head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
58   Adelie     Biscoe            36.5           16.6              181.0   
64   Adelie     Biscoe            36.4           17.1              184.0   
54   Adelie     Biscoe            34.5           18.1              187.0   
98   Adelie      Dream            33.1           16.1              178.0   
116  Adelie  Torgersen            38.6           17.0              188.0   

     body_mass_g     sex  
58        2850.0  Female  
64        2850.0  Female  
54        2900.0  Female  
98        2900.0  Female  
116       2900.0  Female

The following three questions depend on the taxis dataset.

In [75]:
df_taxis = sb.load_dataset('taxis')
df_taxis.head()

pickup              dropoff  passengers  distance  fare   tip  \
0  2019-03-23 20:21:09  2019-03-23 20:27:24           1      1.60   7.0  2.15   
1  2019-03-04 16:11:55  2019-03-04 16:19:00           1      0.79   5.0  0.00   
2  2019-03-27 17:53:01  2019-03-27 18:00:25           1      1.37   7.5  2.36   
3  2019-03-10 01:23:59  2019-03-10 01:49:51           1      7.70  27.0  6.15   
4  2019-03-30 13:27:42  2019-03-30 13:37:14           3      2.16   9.0  1.10   

   tolls  total   color      payment            pickup_zone  \
0    0.0  12.95  yellow  credit card        Lenox Hill West   
1    0.0   9.30  yellow         cash  Upper West Side South   
2    0.0  14.16  yellow  credit card          Alphabet City   
3    0.0  36.95  yellow  credit card              Hudson Sq   
4    0.0  13.40  yellow  credit card           Midtown East   

            dropoff_zone pickup_borough dropoff_borough  
0    UN/Turtle Bay South      Manhattan       Manhattan  
1  Upper West Side South      Manhattan       Manhattan  
2           West Village      Manhattan       Manhattan  
3         Yorkville West      Manhattan       Manhattan  
4         Yorkville West      Manhattan       Manhattan

8. The 'pickup' column contains the date and time the customer picked up, but it's a string.  Add a column to the DataFrame, 'pickup_time', containing the value in 'pickup' as a DateTime.

In [78]:
df_taxis['pickup_time'] = pd.to_datetime(df_taxis['pickup'])
df_taxis['pickup_time'].describe(datetime_is_numeric=True)

count                             6433
mean     2019-03-16 08:31:28.514223616
min                2019-02-28 23:29:03
25%                2019-03-08 15:50:34
50%                2019-03-15 21:46:58
75%                2019-03-23 17:41:38
max                2019-03-31 23:43:45
Name: pickup_time, dtype: object

9. Create a subset of the dataframe to create a new DataFrame, taxis_one_day. This new DataFrame should have pickup_time values between '2019-03-23 00:06:00' (inclusive) and '2019-03-24 00:00:00' (exlusive).

In [79]:
taxis_one_day = df_taxis[(df_taxis['pickup_time']>='2019-03-23 00:06:00') & (df_taxis['pickup_time']<'2019-03-24 00:00:00')]

In [80]:
taxis_one_day['pickup_time'].describe(datetime_is_numeric=True)

count                              209
mean     2019-03-23 14:05:40.722487808
min                2019-03-23 00:07:14
25%                2019-03-23 09:51:43
50%                2019-03-23 15:08:14
75%                2019-03-23 19:22:48
max                2019-03-23 23:50:41
Name: pickup_time, dtype: object

10. From the dataframe in Question 9, take the mean of the numeric columns, grouped at one hour intervals.  Save the result as df_means, and display it.

In [85]:
taxis_one_day.groupby(taxis_one_day.pickup_time.rename('hour').map(lambda x: x.hour)).mean()

passengers  distance       fare       tip     tolls      total
hour                                                                
0       1.000000  1.911667   8.583333  1.415000  0.000000  12.965000
1       1.250000  1.325000   7.875000  1.525000  0.000000  12.575000
2       1.727273  1.739091   8.181818  1.641818  0.000000  13.169091
3       1.500000  3.377500  11.750000  2.410000  0.000000  17.335000
4       2.000000  0.950000   5.500000  0.915000  0.000000  10.215000
5       2.000000  1.270000   6.000000  0.980000  0.000000  10.530000
6       1.000000  0.400000  21.500000  0.000000  0.000000  23.133333
7       2.333333  0.980000   5.250000  1.165000  0.000000   9.298333
8       1.000000  0.020000   2.500000  0.000000  0.000000   3.300000
9       1.500000  1.352000   7.400000  1.674000  0.000000  12.124000
10      1.000000  1.760000   8.750000  0.727500  0.000000  12.152500
11      1.909091  2.070000  11.090909  0.803636  0.000000  14.667273
12      2.000000  2.267143  10.260000  0.645714  0.000000  13.420000
13      2.500000  1.167000   7.550000  2.074000  0.000000  12.344000
14      2.470588  4.752941  18.330000  1.945294  1.003529  24.267059
15      1.000000  6.557143  22.214286  3.210000  1.645714  30.370000
16      2.000000  2.194545  10.454545  1.109091  0.000000  14.431818
17      1.090909  1.913636  14.818182  2.688182  0.523636  20.739091
18      1.571429  3.206429  12.821429  0.844286  0.411429  16.427143
19      1.526316  2.097895  10.263158  1.176316  0.000000  14.226316
20      1.400000  2.448000  11.100000  1.544000  0.000000  15.944000
21      1.000000  2.017143  10.571429  1.420000  0.000000  15.791429
22      1.307692  1.881538   8.923077  1.094615  0.000000  13.433077
23      1.615385  3.725385  15.115385  1.696154  0.000000  20.034615

Check https://colab.research.google.com/github/CodeSolid/CodeSolid.github.io/blob/main/booksource/exercises/PandasExercises.ipynb for more Pandas exercises.